function [r] = generate_rates(time_points,n_trials,aimed_ave_fluctuations)
% Returns ( time_points x n_trials ) matrix with generated syntetic rate traces
% with each columns a trace. 
% Rates are generated by solving dx/dt = -x + J tanh (x) 
% with J nxn matrix with entries taken from a Gaussian distribution with zero mean, g^2/n variance
% The resulted rates are aimed to have fluctuations (x_t-x_{t-1})^2 of aimed_ave_fluctuations 

N = n_trials*2;
dt = 0.05;
run_time = dt:dt:dt*time_points;
g = aimed_ave_fluctuations/35;
J = g*randn(N)/sqrt(N);

f = @(t,x) -x+J*tanh(x);
x0 = (rand(N,1)-0.5)*g;
[treal,xreal] = ode45(f,[0 100],x0); % throw away initial conditions
xreal = xreal';
[treal,xreal] = ode45(f,run_time,xreal(:,end));
r = 10*tanh(xreal(:,1:n_trials));
r = r-min(r(:));
end

